#ifndef LOGCONFIG_H
#define LOGCONFIG_H

#include <QLoggingCategory>
// Define QT Log Categories here
Q_DECLARE_LOGGING_CATEGORY(ChargerComm)
Q_DECLARE_LOGGING_CATEGORY(ChargerMessages)
Q_DECLARE_LOGGING_CATEGORY(OcppComm)
Q_DECLARE_LOGGING_CATEGORY(AuthCache)
Q_DECLARE_LOGGING_CATEGORY(FirmwareUpdate)
Q_DECLARE_LOGGING_CATEGORY(SanityTest)
Q_DECLARE_LOGGING_CATEGORY(Rfid)
Q_DECLARE_LOGGING_CATEGORY(Transactions)
#endif // LOGCONFIG_H
